# Generated by Django 3.0.6 on 2020-05-11 11:53
# flake8: noqa to the file
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('positive_entry', models.CharField(max_length=200, verbose_name='Positive Entry')),
            ],
        ),
    ]
