# Generated by Django 3.0.6 on 2020-05-11 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountclass',
            options={'verbose_name_plural': 'AccountClasses'},
        ),
        migrations.RemoveField(
            model_name='accountclass',
            name='name',
        ),
    ]
