# Generated by Django 3.0.6 on 2020-05-11 22:17
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200511_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclass',
            name='name',
            field=models.CharField(default='asset', max_length=200),
            preserve_default=False,
        ),
    ]
