# Generated by Django 3.0.6 on 2020-05-11 22:22
# flake8: noqa to the file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accountclass_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.AccountClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
