# Generated by Django 3.0.6 on 2020-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20200512_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
