# Generated by Django 3.0.6 on 2020-05-13 09:05

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20200512_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.AccountGroup', verbose_name=accounting.models._Accounting.verbose_class_name),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='account_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.AccountClass', verbose_name=accounting.models._Accounting.verbose_class_name),
        ),
    ]
