# Generated by Django 3.0.6 on 2020-05-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20200513_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='entries',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
