# Generated by Django 3.0.6 on 2020-05-13 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_auto_20200513_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Transaction Date')),
                ('description', models.TextField(verbose_name='Transaction Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(verbose_name='Debit Amount')),
                ('credit', models.FloatField(verbose_name='Credit Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.Account', verbose_name='Account')),
                ('sub_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.SubAccount', verbose_name='Sub-Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.Transaction', verbose_name='transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
