# Generated by Django 3.0.6 on 2020-05-14 01:00
# flake8: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_entry_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='accountclass',
            name='positive_entry',
            field=models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=200, verbose_name='Positive Entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.Transaction', verbose_name='Transaction'),
        ),
    ]
