# Generated by Django 3.0.6 on 2020-05-14 01:14
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20200514_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Transaction Amount'),
            preserve_default=False,
        ),
    ]
